//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineTask2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductMaster
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter product code")]
        [RegularExpression(@"^\d{1}[A-Z]\d{1}[A-Z]\d{5}",
                  ErrorMessage = "Entered product code is not valid. Valid Format: 1P1P12345")]
        public string ProdCode { get; set; }

        [Required(ErrorMessage = "Please enter name")]
        [RegularExpression(@"((?=.*[aeiou])(?!.*[aeiou]{3})(?!.*[a - z &&[^aeiou]]{3})(?!.* ([a - z &&[^eo]])\\1).*)|(\\b([a-zA-Z0-9])\\1\\1+\\b)|([a - z]{3,}|[A-Z]{3,}|\d{3,})",
                   ErrorMessage = "Entered name must contain at least one vowel and name should not like AAA, bbb, xyz etc.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter price")]
        [RegularExpression(@"^\d{0,8}(\.\d{1,4})?$",
                  ErrorMessage = "Entered price is not valid.")]
        public string Price { get; set; }
    }
}
